jupyterhub:
  ingress:
    enabled: true
    hosts:
      - ${domain}

  hub:
    baseUrl: /jupyter/
  proxy:
    service:
      type: NodePort
  singleuser:
    memory:
       guarantee: ${mem_alloc}G
    cpu:
       guarantee: ${cpu_alloc}

# BinderHub config
config:
  BinderHub:
    hub_url: https://${domain}/jupyter
    use_registry: true
    image_prefix: ${docker_id}/${domain}-

service:
  type: NodePort

storage:
  capacity: 2G

ingress:
  enabled: true
  hosts:
    - ${domain}
  annotations:
    kubernetes.io/ingress.class: nginx
  https:
    enabled: true
    type: kube-lego
